currency = {
    "1inch": "1inch Network",
    "aave": "Aave",
    "ada": "Cardano",
    "aed": "阿联酋迪拉姆",
    "afn": "阿富汗尼",
    "algo": "Algorand",
    "all": "阿尔巴尼亚列克",
    "amd": "亚美尼亚德拉姆",
    "amp": "Synereo",
    "ang": "荷属安的列斯盾",
    "aoa": "安哥拉宽扎",
    "ar": "Arweave",
    "ars": "阿根廷比索",
    "atom": "Atomic Coin",
    "aud": "澳大利亚元",
    "avax": "Avalanche",
    "awg": "阿鲁巴弗罗林",
    "axs": "AXS",
    "azn": "阿塞拜疆马纳特",
    "bake": "BakeryToken",
    "bam": "波斯尼亚和黑塞哥维那可兑换马克",
    "bat": "Basic Attention Token",
    "bbd": "巴巴多斯元",
    "bch": "Bitcoin Cash",
    "bdt": "孟加拉国塔卡",
    "bgn": "保加利亚列弗",
    "bhd": "巴林第纳尔",
    "bif": "布隆迪法郎",
    "bmd": "百慕大元",
    "bnb": "币安币",
    "bnd": "文莱元",
    "bob": "玻利维亚诺",
    "brl": "巴西雷亚尔",
    "bsd": "巴哈马元",
    "bsv": "Bitcoin SV",
    "bsw": "Biswap",
    "btc": "比特币",
    "btcb": "比特币BEP2",
    "btg": "比特币黄金",
    "btn": "不丹货币",
    "busd": "币安美元",
    "bwp": "博茨瓦纳普拉",
    "byn": "新白俄罗斯卢布",
    "byr": "白俄罗斯卢布",
    "bzd": "伯利兹元",
    "cad": "加拿大元",
    "cake": "PancakeSwap",
    "cdf": "刚果法郎",
    "celo": "Celo",
    "chf": "瑞士法郎",
    "chz": "Chiliz",
    "clp": "智利比索",
    "cny": "人民币",
    "comp": "Compound Coin",
    "cop": "哥伦比亚比索",
    "crc": "哥斯达黎加科朗",
    "cro": "Crypto.com Chain Token",
    "crv": "Cravy",
    "cuc": "古巴比索",
    "cup": "古巴比索",
    "cve": "佛得角埃斯库多",
    "cvx": "Convex Finance",
    "czk": "捷克克朗",
    "dai": "Dai",
    "dash": "Dash",
    "dcr": "Decred",
    "dfi": "DfiStarter",
    "djf": "吉布提法郎",
    "dkk": "丹麦克朗",
    "doge": "狗狗币",
    "dop": "多米尼加比索",
    "dot": "Dotcoin",
    "dzd": "阿尔及利亚第纳尔",
    "egld": "Elrond",
    "egp": "埃及镑",
    "enj": "Enjin Coin",
    "eos": "EOS",
    "ern": "厄立特里亚纳克法",
    "etb": "埃塞俄比亚比尔",
    "etc": "以太坊经典",
    "eth": "以太币",
    "eur": "欧元",
    "fei": "Fei USD",
    "fil": "FileCoin",
    "fjd": "斐济元",
    "fkp": "福克兰群岛镑",
    "flow": "Flow",
    "frax": "Frax",
    "ftm": "Fantom",
    "ftt": "FarmaTrust",
    "gala": "Gala",
    "gbp": "英镑",
    "gel": "格鲁吉亚拉里",
    "ggp": "GGPro",
    "ghs": "加纳塞地",
    "gip": "直布罗陀镑",
    "gmd": "冈比亚达拉西",
    "gnf": "几内亚法郎",
    "gno": "Gnosis",
    "grt": "Golden Ratio Token",
    "gt": "GateToken",
    "gtq": "危地马拉格查尔",
    "gyd": "圭亚那元",
    "hbar": "Hedera",
    "hkd": "港元",
    "hnl": "洪都拉斯伦皮拉",
    "hnt": "Helium",
    "hot": "Hydro Protocol",
    "hrk": "克罗地亚库纳",
    "ht": "火币币",
    "htg": "海地古德",
    "huf": "匈牙利福林",
    "icp": "Internet Computer",
    "idr": "印尼盾",
    "ils": "以色列新谢克尔",
    "imp": "CoinIMP",
    "inj": "Injective",
    "inr": "印度卢比",
    "iqd": "伊拉克第纳尔",
    "irr": "伊朗里亚尔",
    "isk": "冰岛克朗",
    "jep": "泽西镑",
    "jmd": "牙买加元",
    "jod": "约旦第纳尔",
    "jpy": "日元",
    "kas": "",
    "kava": "Kava",
    "kcs": "Kucoin",
    "kda": "Kadena",
    "kes": "肯尼亚先令",
    "kgs": "吉尔吉斯斯坦索姆",
    "khr": "柬埔寨瑞尔",
    "klay": "Klaytn",
    "kmf": "科摩罗法郎",
    "knc": "Kyber Network",
    "kpw": "朝鲜元",
    "krw": "韩元",
    "ksm": "Kusama",
    "kwd": "科威特第纳尔",
    "kyd": "开曼群岛元",
    "kzt": "哈萨克斯坦腾格",
    "lak": "老挝基普",
    "lbp": "黎巴嫩镑",
    "leo": "LEOcoin",
    "link": "ChainLink",
    "lkr": "斯里兰卡卢比",
    "lrc": "Loopring",
    "lrd": "利比里亚元",
    "lsl": "莱索托洛蒂",
    "ltc": "莱特币",
    "ltl": "立陶宛立特",
    "luna": "Luna Coin",
    "lvl": "拉脱维亚拉特",
    "lyd": "利比亚第纳尔",
    "mad": "摩洛哥迪拉姆",
    "mana": "Decentraland",
    "matic": "Polygon",
    "mdl": "摩尔多瓦列伊",
    "mga": "马达加斯加阿里亚里",
    "mina": "Mina",
    "miota": "IOTA",
    "mkd": "马其顿代纳尔",
    "mkr": "Maker",
    "mmk": "缅甸缅元",
    "mnt": "蒙古图格里克",
    "mop": "澳门币",
    "mro": "毛里塔尼亚乌吉亚",
    "mur": "毛里求斯卢比",
    "mvr": "马尔代夫拉菲亚",
    "mwk": "马拉维克瓦查",
    "mxn": "墨西哥比索",
    "myr": "马来西亚林吉特",
    "mzn": "莫桑比克梅蒂卡尔",
    "nad": "纳米比亚元",
    "near": "NEAR Protocol",
    "neo": "NEO",
    "nexo": "NEXO",
    "ngn": "尼日利亚奈拉",
    "nio": "尼加拉瓜科尔多巴",
    "nok": "挪威克朗",
    "npr": "尼泊尔卢比",
    "nzd": "新西兰元",
    "okb": "Okex",
    "omr": "阿曼里亚尔",
    "one": "Menlo One",
    "pab": "巴拿马巴尔博亚",
    "paxg": "PAX Gold",
    "pen": "秘鲁索尔",
    "pgk": "巴布亚新几内亚基那",
    "php": "菲律宾比索",
    "pkr": "巴基斯坦卢比",
    "pln": "波兰兹罗提",
    "pyg": "巴拉圭瓜拉尼",
    "qar": "卡塔尔里亚尔",
    "qnt": "Quant",
    "qtum": "QTUM",
    "ron": "罗马尼亚列伊",
    "rsd": "塞尔维亚第纳尔",
    "rub": "俄罗斯卢布",
    "rune": "THORChain (ERC20)",
    "rwf": "卢旺达法郎",
    "sand": "BeachCoin",
    "sar": "沙特里亚尔",
    "sbd": "所罗门群岛元",
    "scr": "塞舌尔卢比",
    "sdg": "苏丹镑",
    "sek": "瑞典克朗",
    "sgd": "新加坡元",
    "shib": "Shiba Inu",
    "shp": "圣赫勒拿群岛磅",
    "sle": "",
    "sll": "塞拉利昂利昂",
    "sol": "Sola",
    "sos": "索马里先令",
    "srd": "苏里南元",
    "std": "圣多美和普林西比多布拉 (2018年之前)",
    "stx": "Stox",
    "svc": "萨尔瓦多科朗",
    "syp": "叙利亚镑",
    "szl": "斯威士兰里兰吉尼",
    "thb": "泰铢",
    "theta": "Theta",
    "tjs": "塔吉克斯坦索莫尼",
    "tmt": "土库曼斯坦马纳特",
    "tnd": "突尼斯第纳尔",
    "ton": "Tokamak Network",
    "top": "汤加潘加",
    "trx": "波场币",
    "try": "土耳其里拉",
    "ttd": "特立尼达和多巴哥元",
    "ttt": "Tap Project",
    "tusd": "True USD",
    "twd": "新台币",
    "tzs": "坦桑尼亚先令",
    "uah": "乌克兰格里夫纳",
    "ugx": "乌干达先令",
    "uni": "Universe",
    "usd": "美元",
    "usdc": "USD Coin",
    "usdp": "USDP Stablecoin",
    "usdt": "泰达币",
    "uyu": "乌拉圭比索",
    "uzs": "乌兹别克斯坦索姆",
    "vef": "主权玻利瓦尔",
    "ves": "",
    "vet": "Vechain",
    "vnd": "越南盾",
    "vuv": "瓦努阿图瓦图",
    "waves": "Waves",
    "wbtc": "包装比特币",
    "wemix": "WEMIX",
    "wst": "萨摩亚塔拉",
    "xaf": "中非法郎",
    "xag": "银盎司",
    "xau": "XauCoin",
    "xcd": "东加勒比元",
    "xch": "Chia",
    "xdc": "XDC网络",
    "xdr": "特别提款权",
    "xec": "Eternal Coin",
    "xem": "NEM",
    "xlm": "恒星币",
    "xmr": "门罗币",
    "xof": "西非法郎",
    "xpf": "CFP法郎",
    "xrp": "XRP",
    "xtz": "Tezos",
    "yer": "也门里亚尔",
    "zar": "南非兰特",
    "zec": "ZCash",
    "zil": "Zilliqa",
    "zmk": "赞比亚克瓦查",
    "zmw": "赞比亚克瓦查",
    "zwl": "津巴布韦元",
}
